{{- if or .Values.secret.create .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secrets" .Release.Name) .Values.secret.name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
