name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build release image
        run: docker buildx build --platform linux/amd64 --tag learn-new:${{ github.sha }} --load .
